version: '3.7'

services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_api_example
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
    - "3306:3306"
    tty: true
  app:
    build:
      context: ./Go
#    volumes:
#    - "./Go:/go"
    volumes:
      - type: bind
        source: /home/siddhesh.nikude/grab-tdd-go/TDD-Go/Lab4
        target: /go
    container_name: golang_app
    ports:
    - "8080:8080"
    tty: true
    depends_on:
    - db